sed -i '$ d' test_probs/prob_env_greedymove_pv0_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv1_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv2_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv3_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv4_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv5_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv6_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv7_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv8_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv9_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv10_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv11_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv12_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv13_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv14_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv15_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv16_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv17_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv18_envseed303/test_result.csv
sed -i '$ d' test_probs/prob_env_greedymove_pv19_envseed303/test_result.csv
